# Generated by Django 5.2 on 2025-05-01 12:13

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_category_status_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='type', chained_model_field='type', on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
